global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'mock-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mock-service:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']